<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Doaco_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get doaco by id_doacoes
     */
    function get_doaco($id_doacoes)
    {
        return $this->db->limit(15)->get_where('doacoes',array('id_doacoes'=>$id_doacoes))->row_array();
    }
    
    function get_doaco_limit($id_us)
    {
        return $this->db->query("SELECT * FROM doacoes WHERE id_us = '".$id_us."' limit 20;")->result_array();
    }
        
    /*
     * Get all doacoes
     */
    function get_all_doacoes()
    {
        $this->db->order_by('id_doacoes', 'desc');
        return $this->db->get('doacoes')->result_array();
    }
        
    /*
     * function to add new doaco
     */
    function add_doaco($params)
    {
        $this->db->insert('doacoes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update doaco
     */
    function update_doaco($id_doacoes,$params)
    {
        $this->db->where('id_doacoes',$id_doacoes);
        return $this->db->update('doacoes',$params);
    }
    
    /*
     * function to delete doaco
     */
    function delete_doaco($id_doacoes)
    {
        return $this->db->delete('doacoes',array('id_doacoes'=>$id_doacoes));
    }
}