<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gasto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gasto by id_gastos
     */
    function get_gasto($id_gastos)
    {
        return $this->db->get_where('gastos',array('id_gastos'=>$id_gastos))->row_array();
    }
        
    /*
     * Get all gastos
     */
    function get_all_gastos()
    {
        $this->db->order_by('id_gastos', 'desc');
        return $this->db->limit(15)->get('gastos')->result_array();
    }
        
    /*
     * function to add new gasto
     */
    function add_gasto($params)
    {
        $this->db->insert('gastos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gasto
     */
    function update_gasto($id_gastos,$params)
    {
        $this->db->where('id_gastos',$id_gastos);
        return $this->db->update('gastos',$params);
    }
    
    /*
     * function to delete gasto
     */
    function delete_gasto($id_gastos)
    {
        return $this->db->delete('gastos',array('id_gastos'=>$id_gastos));
    }
}